-- Revoke default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA whatsmeow
REVOKE ALL PRIVILEGES ON TABLES FROM wuzapi;

ALTER DEFAULT PRIVILEGES IN SCHEMA whatsmeow
REVOKE ALL PRIVILEGES ON SEQUENCES FROM wuzapi;

-- Revoke privileges on schema
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA whatsmeow FROM wuzapi;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA whatsmeow FROM wuzapi;
REVOKE USAGE ON SCHEMA whatsmeow FROM wuzapi;

-- Drop the schema
DROP SCHEMA IF EXISTS whatsmeow CASCADE;
