name: Go-Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Clear Go module cache
      run: go clean -modcache

    - name: Verify dependencies
      run: go mod verify
      
    - name: Install dependencies
      run: go mod tidy

    - name: Install golangci-lint
      run: |
        LINT_VERSION=v1.55.2
        GO_BIN=$(go env GOPATH)/bin

        if ! command -v golangci-lint &> /dev/null; then
          echo "Installing golangci-lint version $LINT_VERSION..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GO_BIN" "$LINT_VERSION"
        else
          echo "golangci-lint is already installed."
        fi


    - name: Run golangci-lint
      run: golangci-lint run -v ./...
