name: Shell Script Lint

on:
  push:
    branches: [main]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt install shellcheck

      - name: Run ShellCheck
        run: |
          shopt -s globstar nullglob
          shellcheck --severity=warning --format=gcc **/*.sh
        
      - name: Summarize ShellCheck results
        if: always()
        run: |
          echo "ShellCheck Summary:"
          echo "==================="
          grep -E '^.+:\d+:\d+: (warning|error)' shellcheck_output.txt | sort | uniq -c | sort -rn

  actionlint:
    name: ActionLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color